theme: jekyll-theme-cayman
show_downloads: True
navigation:
  - title: Home
    url: /
  - title: Application Setup
    url: setup
  - title: Process the Data
    url: process_data
  - title: Run the Application
    url: runningApplication
  - title: Extras
    url: extras
  - title: ITCR Connectivity
    url: itcr_connectivity
  - title: RANO Federation
    url: rano_federation